### ISSUE TITLE
Data extraction mods

### ISSUE THREAD

**Issue by vrodriguezf** [mit-ll/spacegym-kspdg#5]
Following my question during the kick-off meeting about the possibility of using KSP mods to extract data that can potentially augment the observation space, these are the mods I was talking about:

1. [KSP Data Export](https://forum.kerbalspaceprogram.com/topic/201967-112x-export-flight-data-to-a-csv-file-mod/): It extracts the following information:

```
Vessel
- Surface Velocity
- G-Force
- Acceleration
- Thrust
- TWR
- Mass
 
Position
- Altitude (Terrain)
- Altitude (Sea Level)
- Downrange Distance
- Latitude
- Longitude

Orbit
- Apoapsis
- Periapsis
- Inclination
- Orbital Velocity

Target
- Distance
- Target Velocity

Resources
- Stage DeltaV
- Vessel DeltaV

Science
- Air Pressure
```

2. [Kaptain's Log](https://forum.kerbalspaceprogram.com/topic/165482-112x-the-kaptains-log/): 
```
Events Recorded (not complete)

- Flight Log Recorded
- Part Died
- Launch
- Stage Separation
- Part Couple (dock)
- Vessel Modified
- Stage Activate
- Orbit Closed (enter orbit, not from a launch)
- Orbit Escaped (achieve escape velocity)
- Vessel Recovered
- Landed
- Crew Modified
- Progress Record
- Kerbal Passed Out From Gee Force
- Crew Killed
- Crew Transferred
- Dominant Body Change (SOI change)
- Flag Plant
- Crew On EVA
- Manual Entry

Data items being captured are:
- Vessel name (or Kerbal name)
- Universal Time
- UTC time
- Mission Time
- Situation
- Body (which SOI is the vessel in)
- Control level
- Altitude
- Speed
- Event type
- Notes (entered by player)
- Screenshot (both full size and thumbnail)
``

Best!
Víctor

**Comment by rallen10** [comment]
@vrodriguezf good question. It seems perfectly reasonable to use such tools for development of your agent---especially for post-hoc analysis purposes. 

I suppose the one point of concern is that this may prove to be incompatible with the evaluation rounds at the semi-finals and the finals. We still need to hammer down the details on how those rounds will work, but there is the strong possibility that participants will submit their agents for evaluation on a centralized/managed computer system running KSP. If we do take this centralized evaluation route for the semi-finals and finals, we won't be able to guarantee that we will have these mods installed.

Therefore, all I can say at the moment is that I would proceed with caution. If you are in anyway collecting information outside of the [environment's observation space](https://github.com/mit-ll/spacegym-kspdg/blob/ce7190c57bfb5e0ff73734cd74401d6a44565983/src/kspdg/pe1/pe1_base.py#L166) and using that to drive your agent's decision making process, then you run the strong risk of making the agent incompatible with future evaluation pipelines.

Please let me know how/if you end up using these mods. It may affect how we run the evaluation.

**Comment by vrodriguezf** [comment]
Ok thank you! It makes sense, hadn't thought about the future evaluations.
